# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4460b6897302502f27aed98caf3528d4"
name = "VolumeShip"
handle = "volumeship"

application_url = "https://expanded-memo-view-americas.trycloudflare.com"

embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "my-remix-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_metaobject_definitions,write_metaobjects,write_products,write_themes,read_metaobjects"

[auth]

redirect_urls = ["https://expanded-memo-view-americas.trycloudflare.com/auth/callback", "https://expanded-memo-view-americas.trycloudflare.com/auth/shopify/callback", "https://expanded-memo-view-americas.trycloudflare.com/api/auth/callback"]

[webhooks]
api_version = "2025-07"

[pos]
embedded = false
